### PR TITLE
New Spanish Language Files (Ver. 6.0.0)

### PR DESCRIPTION
**Pull request by ArxelDev**
I did a full translation of the file from the primary language to Spanish, as the old files were incomplete and outdated.

I also included more variants of Spanish that were missing, which were:

Spanish Argentine 
*********Ecuador
******** Chile
******** Mexico
*******Uruguay
******* Venezuela

### CODE REVIEW

**Review by mysticdrew — APPROVED** [review]
Thank you very much!!

**Comment by ArxelDev** [comment]
You're welcome, always on order.
Soon I will see if I translate the mod's web docs.

And thanks to you for creating such a good mod. 🙂
@mysticdrew

**Comment by mysticdrew** [comment]
> You're welcome, always on order. Soon I will see if I translate the mod's web docs.
> 
> And thanks to you for creating such a good mod. 🙂 @mysticdrew

Sounds great, might be helpful to come into our discord and work with our docs person on getting setup for translating the site documentation.

**Comment by ArxelDev** [comment]
> > You're welcome, always on order. Soon I will see if I translate the mod's web docs.
> > 
> > And thanks to you for creating such a good mod. 🙂 @mysticdrew
> 
> Sounds great, might be helpful to come into our discord and work with our docs person on getting setup for translating the site documentation. 

It seems good to me, I am willing to work with the staff in charge of the docs.

I've been on your discord for a while now, I even talked to you. Let me introduce myself so you know who I am.
@mysticdrew

**Pull request merged**
